"""Generate supabase/seed.sql from the data the app already has.

The seed is NOT hand-written. It is derived from two sources that are already
the truth:

    public/models/products/catalog.json   shops, products, placements
    blender/houseluxe/config/plan_3bed    rooms and their finishes

so the database starts out agreeing with the 3D scene instead of drifting from
it on day one. Re-run after changing either.

    python supabase/generate_seed.py

The plan config is pure dataclasses with no Blender imports, which is what
makes reading it from plain Python possible.
"""

from __future__ import annotations

import json
import os
import sys
from datetime import datetime

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
sys.path.insert(0, os.path.join(REPO, "blender"))

from houseluxe.config.plan_3bed import PLAN  # noqa: E402

CATALOG_PATH = os.path.join(REPO, "public", "models", "products", "catalog.json")
OUT_PATH = os.path.join(HERE, "seed.sql")

SCENE_SLUG = PLAN.name          # "3bed"
SCENE_NAME = "3 Bedroom Family Home"


def q(value) -> str:
    """SQL literal for a value, or NULL."""
    if value is None or value == "":
        return "null"
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)
    return "'" + str(value).replace("'", "''") + "'"


def cents(price) -> str:
    return "null" if price is None else str(int(round(float(price) * 100)))


# Blender ProductCategory -> (category code, kind). Categories the catalogue
# can emit but nobody stocks yet are still seeded, so a shop can pick them.
CATEGORIES = [
    ("sofa", "Sofas", "object", 10),
    ("chair", "Chairs", "object", 20),
    ("table", "Tables", "object", 30),
    ("bed", "Beds", "object", 40),
    ("storage", "Storage", "object", 50),
    ("television", "Televisions", "object", 60),
    ("appliance", "Appliances", "object", 70),
    ("lighting", "Lighting", "object", 80),
    ("decor", "Decor", "object", 90),
    ("rug", "Rugs", "object", 100),
    ("bath", "Baths", "object", 110),
    ("basin", "Basins", "object", 120),
    ("toilet", "Toilets", "object", 130),
    ("shower", "Showers", "object", 140),
    ("kitchen_unit", "Kitchen Units", "object", 150),
    ("tile", "Tiles", "finish", 200),
    ("paint", "Paint", "finish", 210),
    ("brick", "Brick & Cladding", "finish", 220),
    ("flooring", "Flooring", "finish", 230),
    ("roofing", "Roofing", "finish", 240),
    ("window", "Windows", "object", 250),
    ("door", "Doors", "object", 260),
]

PLANS = [
    # code, name, price/mo, products, placements, scenes, analytics, featured
    ("starter", "Starter", 0, 5, 2, 1, False, False),
    ("growth", "Growth", 750, 40, 12, 3, True, False),
    ("premier", "Premier", 2500, None, None, None, True, True),
]


def main() -> int:
    if not os.path.exists(CATALOG_PATH):
        print(f"missing {CATALOG_PATH} -- run the Blender build first")
        return 1

    catalog = json.load(open(CATALOG_PATH, encoding="utf-8"))
    out: list[str] = []
    w = out.append

    w("-- =========================================================================")
    w("-- HomeLuxe 3D -- seed data")
    w("--")
    w("-- GENERATED by supabase/generate_seed.py. Do not edit by hand; edit the")
    w("-- Blender catalogue or the plan and re-run, or the database and the 3D")
    w("-- scene will disagree.")
    w(f"-- Generated {datetime.now().isoformat(timespec='seconds')}")
    w("-- =========================================================================")
    w("")
    w("begin;")
    w("")

    # -- Reference data ----------------------------------------------------
    w("-- Product categories")
    w("insert into product_categories (code, name, kind, sort_order) values")
    rows = [f"  ({q(c)}, {q(n)}, {q(k)}, {o})" for c, n, k, o in CATEGORIES]
    w(",\n".join(rows))
    w("on conflict (code) do update set name = excluded.name, kind = excluded.kind;")
    w("")

    w("-- Subscription plans")
    w("insert into plans (code, name, price_cents, max_products, max_placements,"
      " max_scenes, analytics, featured) values")
    rows = []
    for code, name, price, prod, plc, scn, ana, feat in PLANS:
        rows.append(
            f"  ({q(code)}, {q(name)}, {price * 100}, {q(prod)}, {q(plc)}, "
            f"{q(scn)}, {q(ana)}, {q(feat)})"
        )
    w(",\n".join(rows))
    w("on conflict (code) do nothing;")
    w("")

    # -- Scene and rooms ---------------------------------------------------
    w("-- Scene")
    w(f"insert into scenes (slug, name, description, model_base, is_published) values")
    w(f"  ({q(SCENE_SLUG)}, {q(SCENE_NAME)}, "
      f"{q('Three bedroom family home with pool, generated from blender/houseluxe.')}, "
      f"{q('/models/')}, true)")
    w("on conflict (slug) do update set name = excluded.name, is_published = true;")
    w("")

    w("-- Rooms, from blender/houseluxe/config/plan_3bed.py")
    w("insert into rooms (scene_id, code, name, room_type, x0_mm, y0_mm, x1_mm, y1_mm, sort_order)")
    w("select s.id, v.code, v.name, v.rtype::room_type, v.x0, v.y0, v.x1, v.y1, v.ord")
    w("from scenes s, (values")
    rows = []
    for i, room in enumerate(PLAN.rooms):
        rows.append(
            f"  ({q(room.name)}, {q(room.label)}, {q(room.room_type)}, {room.x0}, {room.y0}, "
            f"{room.x1}, {room.y1}, {i * 10})"
        )
    w(",\n".join(rows))
    w(") as v(code, name, rtype, x0, y0, x1, y1, ord)")
    w(f"where s.slug = {q(SCENE_SLUG)}")
    w("on conflict (scene_id, code) do update set name = excluded.name, "
      "room_type = excluded.room_type;")
    w("")

    # -- Shops -------------------------------------------------------------
    w("-- Shops")
    w("insert into shops (slug, name, tagline, currency, status) values")
    rows = []
    for shop in catalog["shops"]:
        rows.append(
            f"  ({q(shop['id'])}, {q(shop['name'])}, {q(shop.get('tagline'))}, "
            f"{q(shop.get('currency', 'BWP'))}, 'active')"
        )
    w(",\n".join(rows))
    w("on conflict (slug) do update set name = excluded.name, "
      "tagline = excluded.tagline, status = 'active';")
    w("")

    w("-- Every seeded shop starts on the Growth plan so its products are live.")
    w("-- shop_is_live() gates public visibility on an active subscription, so")
    w("-- without this nothing would render.")
    w("insert into shop_subscriptions (shop_id, plan_id, status, current_period_end)")
    w("select s.id, p.id, 'active', now() + interval '1 year'")
    w("from shops s cross join plans p")
    w(f"where p.code = 'growth' and s.slug in "
      f"({', '.join(q(s['id']) for s in catalog['shops'])})")
    w("  and not exists (select 1 from shop_subscriptions x where x.shop_id = s.id);")
    w("")

    # -- Products ----------------------------------------------------------
    w("-- Products")
    w("insert into products (shop_id, slug, sku, name, description, category_code,")
    w("                      status, price_cents, currency, width_mm, depth_mm, height_mm)")
    w("select sh.id, v.slug, v.sku, v.name, v.descr, v.cat, 'published',")
    w("       v.price, v.cur, v.w, v.d, v.h")
    w("from shops sh join (values")
    rows = []
    for shop in catalog["shops"]:
        for p in shop["products"]:
            # qualified id is "<shop>.<product>"; strip the shop prefix.
            slug = p["id"].split(".", 1)[1]
            dims = p.get("dimensions") or {}
            rows.append(
                f"  ({q(shop['id'])}, {q(slug)}, {q(p.get('sku'))}, {q(p['name'])},\n"
                f"   {q(p.get('description'))}, {q(p['category'])}, {cents(p.get('price'))},"
                f" {q(p.get('currency', 'BWP'))},\n"
                f"   {q(dims.get('width'))}, {q(dims.get('depth'))}, {q(dims.get('height'))})"
            )
    w(",\n".join(rows))
    w(") as v(shop, slug, sku, name, descr, cat, price, cur, w, d, h)")
    w("  on sh.slug = v.shop")
    w("on conflict (shop_id, slug) do update set")
    w("  name = excluded.name, description = excluded.description,")
    w("  price_cents = excluded.price_cents, status = 'published';")
    w("")

    # -- Variants ----------------------------------------------------------
    w("-- Default variant per product. Objects carry a model; finishes carry a")
    w("-- material name and texture instead.")
    w("insert into product_variants (product_id, slug, name, sku, price_cents,")
    w("                              model_url, material_name, texture_url,")
    w("                              texture_tile_mm, is_default)")
    w("select p.id, 'default', v.name, v.sku, p.price_cents,")
    w("       v.model, v.material, v.texture, v.tile_mm, true")
    w("from products p")
    w("join shops sh on sh.id = p.shop_id")
    w("join (values")
    rows = []
    for shop in catalog["shops"]:
        for p in shop["products"]:
            slug = p["id"].split(".", 1)[1]
            dims = p.get("dimensions") or {}
            tile_mm = dims.get("width") if p.get("material") else None
            rows.append(
                f"  ({q(shop['id'])}, {q(slug)}, {q(p['name'])}, {q(p.get('sku'))},\n"
                f"   {q(p.get('model'))}, {q(p.get('material'))}, "
                f"{q(p.get('texture'))}, {q(tile_mm)})"
            )
    w(",\n".join(rows))
    w(") as v(shop, slug, name, sku, model, material, texture, tile_mm)")
    w("  on sh.slug = v.shop and p.slug = v.slug")
    w("on conflict (product_id, slug) do update set")
    w("  model_url = excluded.model_url, material_name = excluded.material_name,")
    w("  texture_url = excluded.texture_url;")
    w("")

    # Colour variants. Gamazine and paint are one product each, sold in many
    # shades, and each shade supplies its own material so two walls in
    # different colours stay distinguishable.
    variant_rows = []
    for shop in catalog["shops"]:
        for prod in shop["products"]:
            for var in prod.get("variants") or []:
                variant_rows.append(
                    f"  ({q(shop['id'])}, {q(prod['id'].split('.', 1)[1])}, "
                    f"{q(var['slug'])}, {q(var['name'])}, {q(var['sku'])},"
                    f" {q(var['material'])}, {q(var.get('texture'))},"
                    f" {q(var.get('swatch'))}, {q(var['isDefault'])})"
                )
    if variant_rows:
        w("-- Colour variants.")
        w("insert into product_variants (product_id, slug, name, sku,")
        w("                              material_name, texture_url, is_default)")
        w("select p.id, v.slug, v.name, v.sku, v.material, v.texture, false")
        w("from products p join shops sh on sh.id = p.shop_id")
        w("join (values")
        w(",\n".join(variant_rows))
        w(") as v(shop, prod, slug, name, sku, material, texture, swatch, is_def)")
        w("  on sh.slug = v.shop and p.slug = v.prod")
        w("on conflict (product_id, slug) do update set")
        w("  material_name = excluded.material_name;")
        w("")

    # -- Promotions --------------------------------------------------------
    # One row per distinct special, then linked to the products carrying it.
    # The end date is what makes a product go dark on its own.
    promos = {}
    for shop in catalog["shops"]:
        for prod in shop["products"]:
            promo = prod.get("promotion")
            if promo:
                promos.setdefault((shop["id"], promo["label"]), promo)

    if promos:
        w("-- Promotions. product_is_active() stops advertising a product once")
        w("-- its promotion's ends_on has passed -- no job, nothing deleted.")
        w("insert into promotions (shop_id, label, terms, starts_on, ends_on, promo_price_cents)")
        w("select sh.id, v.label, v.terms, v.starts::date, v.ends::date, v.price::integer")
        w("from shops sh join (values")
        rows = []
        for (shop_id, label), promo in promos.items():
            rows.append(
                f"  ({q(shop_id)}, {q(label)}, {q(promo.get('terms'))}, "
                f"{q(promo.get('startsOn'))}, {q(promo.get('endsOn'))}, "
                f"{cents(promo.get('promoPrice'))})"
            )
        w(",\n".join(rows))
        w(") as v(shop, label, terms, starts, ends, price) on sh.slug = v.shop")
        w("where not exists (")
        w("  select 1 from promotions x where x.shop_id = sh.id and x.label = v.label")
        w(");")
        w("")

        w("-- Link products to their promotion.")
        w("update products p set promotion_id = pr.id")
        w("from promotions pr, shops sh")
        w("where pr.shop_id = sh.id and p.shop_id = sh.id")
        w("  and (sh.slug, p.slug, pr.label) in (")
        rows = []
        for shop in catalog["shops"]:
            for prod in shop["products"]:
                promo = prod.get("promotion")
                if promo:
                    rows.append(
                        f"    ({q(shop['id'])}, {q(prod['id'].split('.', 1)[1])}, "
                        f"{q(promo['label'])})"
                    )
        w(",\n".join(rows))
        w("  );")
        w("")

    # -- Room scoping ------------------------------------------------------
    # No rows for a product means it suits ANY room, so only scoped products
    # appear here. The jute rug is deliberately absent.
    scoped = []
    for shop in catalog["shops"]:
        for prod in shop["products"]:
            for rt in prod.get("roomTypes") or []:
                scoped.append((shop["id"], prod["id"].split(".", 1)[1], rt))

    if scoped:
        w("-- Room scoping. Absent = suits any room.")
        w("insert into product_room_types (product_id, room_type)")
        w("select p.id, v.rt::room_type")
        w("from products p join shops sh on sh.id = p.shop_id")
        w("join (values")
        w(",\n".join(
            f"  ({q(a)}, {q(b)}, {q(c)})" for a, b, c in scoped))
        w(") as v(shop, slug, rt) on sh.slug = v.shop and p.slug = v.slug")
        w("on conflict (product_id, room_type) do nothing;")
        w("")

    # -- Slots -------------------------------------------------------------
    # One slot per existing placement, so the current hand-authored layout
    # becomes sellable inventory rather than being thrown away.
    all_placements = catalog["houses"].get(SCENE_SLUG, [])
    # Object slots only. A finish has no position -- it dresses a surface --
    # and gets its own slot from the wall and floor sections below.
    placements = [p for p in all_placements if not p.get("isFinish")]
    w("-- Placement slots. Derived from the hand-authored layout: each existing")
    w("-- placement becomes a slot, so the current arrangement turns into")
    w("-- inventory that can be re-sold rather than being fixed forever.")
    w("insert into placement_slots (scene_id, room_id, code, label, category_code,")
    w("                             kind, room_type, x_mm, y_mm, z_mm, rotation_deg,")
    w("                             max_width_mm, max_depth_mm, is_premium)")
    w("select sc.id, r.id, v.code, v.label, v.cat, v.kind::product_kind,")
    w("       r.room_type, v.x, v.y, v.z, v.rot, v.maxw, v.maxd, v.premium")
    w("from scenes sc")
    w("cross join (values")

    by_product = {}
    for shop in catalog["shops"]:
        for p in shop["products"]:
            by_product[p["id"]] = p

    rows = []
    for i, pl in enumerate(placements):
        product = by_product.get(pl["product"], {})
        dims = product.get("dimensions") or {}
        # Positions in the manifest are three.js metres; convert back to the
        # scene's own millimetres, which is what the database stores.
        x_m, _y_m, z_m = pl["position"]
        x_mm = round(x_m * 1000.0, 1)
        y_mm = round(-z_m * 1000.0, 1)
        code = f"{pl['room']}-{product.get('category', 'item')}-{i + 1}"
        label = f"{pl['room'].title()} {product.get('category', 'item')} position"
        maxw = (dims.get("width") or 0) * 1.15 or None
        maxd = (dims.get("depth") or 0) * 1.15 or None
        premium = product.get("category") in ("sofa", "television")
        rows.append(
            f"  ({q(pl['room'])}, {q(code)}, {q(label)}, "
            f"{q(product.get('category'))}, 'object',\n"
            f"   {x_mm}, {y_mm}, 0, {pl.get('rotationY', 0)}, "
            f"{q(round(maxw, 1) if maxw else None)}, "
            f"{q(round(maxd, 1) if maxd else None)}, {q(premium)})"
        )
    w(",\n".join(rows))
    w(") as v(room_code, code, label, cat, kind, x, y, z, rot, maxw, maxd, premium)")
    w("left join rooms r on r.scene_id = sc.id and r.code = v.room_code")
    w(f"where sc.slug = {q(SCENE_SLUG)}")
    w("on conflict (scene_id, code) do update set label = excluded.label;")
    w("")

    # -- Placements --------------------------------------------------------
    w("-- Live placements: fill each slot with the product it was authored with.")
    w("insert into placements (scene_id, slot_id, variant_id, shop_id, status, note)")
    w("select sc.id, sl.id, pv.id, p.shop_id, 'live', v.note")
    w("from scenes sc")
    w("join (values")
    rows = []
    for i, pl in enumerate(placements):
        product = by_product.get(pl["product"], {})
        code = f"{pl['room']}-{product.get('category', 'item')}-{i + 1}"
        shop_slug, product_slug = pl["product"].split(".", 1)
        rows.append(
            f"  ({q(code)}, {q(shop_slug)}, {q(product_slug)}, {q(pl.get('note'))})"
        )
    w(",\n".join(rows))
    w(") as v(slot_code, shop, product, note) on true")
    w("join placement_slots sl on sl.scene_id = sc.id and sl.code = v.slot_code")
    w("join shops sh on sh.slug = v.shop")
    w("join products p on p.shop_id = sh.id and p.slug = v.product")
    w("join product_variants pv on pv.product_id = p.id and pv.is_default")
    w(f"where sc.slug = {q(SCENE_SLUG)}")
    w("  and not exists (")
    w("    select 1 from placements x where x.slot_id = sl.id and x.status = 'live'")
    w("  );")
    w("")

    # -- Surface finishes ---------------------------------------------------
    finishes = [
        (r.name, r.finish) for r in PLAN.rooms
        if r.finish.startswith("tile_") or r.finish in ("carpet", "timber")
    ]
    w("-- Finish slots: which product dresses which room's floor. This is what")
    w("-- makes \"who supplied this floor?\" answerable for any surface.")
    w("insert into placement_slots (scene_id, room_id, code, label, category_code,")
    w("                             kind, room_type, material_name)")
    w("select sc.id, r.id, 'floor-' || r.code, r.name || ' floor', 'tile',")
    w("       'finish'::product_kind, r.room_type, v.material")
    w("from scenes sc")
    w("join (values")
    rows = [f"  ({q(name)}, {q(finish)})" for name, finish in finishes]
    w(",\n".join(rows))
    w(") as v(room_code, material) on true")
    w("join rooms r on r.scene_id = sc.id and r.code = v.room_code")
    w(f"where sc.slug = {q(SCENE_SLUG)}")
    w("on conflict (scene_id, code) do update set material_name = excluded.material_name;")
    w("")

    # -- Wall surfaces -----------------------------------------------------
    # One paintable surface per room plus the exterior, matching the skins
    # Blender exports. These are what a paint or coating is placed ON.
    w("-- Wall surfaces: one slot per room, plus the exterior.")
    w("insert into placement_slots (scene_id, room_id, code, label, category_code,")
    w("                             kind, room_type, material_name)")
    w("select sc.id, r.id, 'wall-' || r.code, r.name || ' walls', 'paint',")
    w("       'finish'::product_kind, r.room_type, 'wall.' || r.code")
    w("from scenes sc join rooms r on r.scene_id = sc.id")
    w(f"where sc.slug = {q(SCENE_SLUG)}")
    w("on conflict (scene_id, code) do update set material_name = excluded.material_name;")
    w("")
    w("insert into placement_slots (scene_id, code, label, category_code,")
    w("                             kind, room_type, material_name)")
    w("select sc.id, 'wall-exterior', 'Exterior walls', 'paint',")
    w("       'finish'::product_kind, 'outdoor'::room_type, 'wall.exterior'")
    w(f"from scenes sc where sc.slug = {q(SCENE_SLUG)}")
    w("on conflict (scene_id, code) do nothing;")
    w("")

    # -- Finish placements -------------------------------------------------
    # A finish slot names a MATERIAL; a finish product SUPPLIES one. Matching
    # them is what makes "which shop supplied this floor?" answerable from the
    # database rather than only from the baked .glb.
    #
    # Slots whose material nobody sells (the robe's carpet) stay empty, which
    # is correct: that floor is not advertising anything.
    w("-- Fill finish slots by matching the slot's material to the product")
    w("-- that supplies it. Unsold materials leave their slot empty.")
    w("insert into placements (scene_id, slot_id, variant_id, shop_id, status, note)")
    w("select sl.scene_id, sl.id, v.id, p.shop_id, 'live',")
    w("       'Floor finish supplied by ' || sh.name")
    w("from placement_slots sl")
    w("join scenes sc on sc.id = sl.scene_id")
    w("join product_variants v on v.material_name = sl.material_name")
    w("join products p on p.id = v.product_id")
    w("join shops sh on sh.id = p.shop_id")
    w("where sl.kind = 'finish'")
    w("  and sl.material_name is not null")
    w("  and p.status = 'published'")
    w(f"  and sc.slug = {q(SCENE_SLUG)}")
    w("  and not exists (")
    w("    select 1 from placements x where x.slot_id = sl.id and x.status = 'live'")
    w("  );")
    w("")

    w("commit;")
    w("")

    with open(OUT_PATH, "w", encoding="utf-8") as handle:
        handle.write("\n".join(out))

    counts = {
        "shops": len(catalog["shops"]),
        "products": sum(len(s["products"]) for s in catalog["shops"]),
        "rooms": len(PLAN.rooms),
        "placements": len(placements),
        "finish slots": len(finishes),
    }
    print(f"wrote {OUT_PATH}")
    for key, value in counts.items():
        print(f"  {key:<14} {value}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
