"""Generate supabase/seed.sql from the data the app already has.

The seed is NOT hand-written. It is derived from two sources that are already
the truth:

    public/models/products/catalog.json   shops, products, placements
    blender/houseluxe/config/plan_3bed    rooms and their finishes

so the database starts out agreeing with the 3D scene instead of drifting from
it on day one. Re-run after changing either.

    python supabase/generate_seed.py

The plan config is pure dataclasses with no Blender imports, which is what
makes reading it from plain Python possible.
"""

from __future__ import annotations

import json
import os
import sys
from datetime import datetime

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.dirname(HERE)
sys.path.insert(0, os.path.join(REPO, "blender"))

from houseluxe.config.plan_3bed import PLAN  # noqa: E402
from houseluxe.config.slots_3bed import SLOTS  # noqa: E402

CATALOG_PATH = os.path.join(REPO, "public", "models", "products", "catalog.json")
OUT_PATH = os.path.join(HERE, "seed.sql")

SCENE_SLUG = PLAN.name          # "3bed"
SCENE_NAME = "3 Bedroom Family Home"


def q(value) -> str:
    """SQL literal for a value, or NULL."""
    if value is None or value == "":
        return "null"
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return str(value)
    return "'" + str(value).replace("'", "''") + "'"


def cents(price) -> str:
    return "null" if price is None else str(int(round(float(price) * 100)))


# Blender ProductCategory -> (category code, kind). Categories the catalogue
# can emit but nobody stocks yet are still seeded, so a shop can pick them.
CATEGORIES = [
    ("sofa", "Sofas", "object", 10),
    ("chair", "Chairs", "object", 20),
    ("table", "Tables", "object", 30),
    ("bed", "Beds", "object", 40),
    ("storage", "Storage", "object", 50),
    ("television", "Televisions", "object", 60),
    ("appliance", "Appliances", "object", 70),
    ("lighting", "Lighting", "object", 80),
    ("decor", "Decor", "object", 90),
    ("rug", "Rugs", "object", 100),
    ("bath", "Baths", "object", 110),
    ("basin", "Basins", "object", 120),
    ("toilet", "Toilets", "object", 130),
    ("shower", "Showers", "object", 140),
    ("kitchen_unit", "Kitchen Units", "object", 150),
    ("tile", "Tiles", "finish", 200),
    ("paint", "Paint", "finish", 210),
    ("brick", "Brick & Cladding", "finish", 220),
    ("flooring", "Flooring", "finish", 230),
    ("roofing", "Roofing", "finish", 240),
    ("window", "Windows", "object", 250),
    ("door", "Doors", "object", 260),
    ("hardware", "Door & Window Hardware", "object", 270),
]

PLANS = [
    # code, name, price/mo, products, placements, scenes, analytics, featured
    ("starter", "Starter", 0, 5, 2, 1, False, False),
    ("growth", "Growth", 750, 40, 12, 3, True, False),
    ("premier", "Premier", 2500, None, None, None, True, True),
]


def main() -> int:
    if not os.path.exists(CATALOG_PATH):
        print(f"missing {CATALOG_PATH} -- run the Blender build first")
        return 1

    catalog = json.load(open(CATALOG_PATH, encoding="utf-8"))
    out: list[str] = []
    w = out.append

    w("-- =========================================================================")
    w("-- HomeLuxe 3D -- seed data")
    w("--")
    w("-- GENERATED by supabase/generate_seed.py. Do not edit by hand; edit the")
    w("-- Blender catalogue or the plan and re-run, or the database and the 3D")
    w("-- scene will disagree.")
    w(f"-- Generated {datetime.now().isoformat(timespec='seconds')}")
    w("-- =========================================================================")
    w("")
    w("begin;")
    w("")

    # -- Reference data ----------------------------------------------------
    w("-- Product categories")
    w("insert into product_categories (code, name, kind, sort_order) values")
    rows = [f"  ({q(c)}, {q(n)}, {q(k)}, {o})" for c, n, k, o in CATEGORIES]
    w(",\n".join(rows))
    w("on conflict (code) do update set name = excluded.name, kind = excluded.kind;")
    w("")

    w("-- Subscription plans")
    w("insert into plans (code, name, price_cents, max_products, max_placements,"
      " max_scenes, analytics, featured) values")
    rows = []
    for code, name, price, prod, plc, scn, ana, feat in PLANS:
        rows.append(
            f"  ({q(code)}, {q(name)}, {price * 100}, {q(prod)}, {q(plc)}, "
            f"{q(scn)}, {q(ana)}, {q(feat)})"
        )
    w(",\n".join(rows))
    w("on conflict (code) do nothing;")
    w("")

    # -- Scene and rooms ---------------------------------------------------
    w("-- Scene")
    w(f"insert into scenes (slug, name, description, model_base, is_published) values")
    w(f"  ({q(SCENE_SLUG)}, {q(SCENE_NAME)}, "
      f"{q('Three bedroom family home with pool, generated from blender/houseluxe.')}, "
      f"{q('/models/')}, true)")
    w("on conflict (slug) do update set name = excluded.name, is_published = true;")
    w("")

    w("-- Rooms, from blender/houseluxe/config/plan_3bed.py")
    w("insert into rooms (scene_id, code, name, room_type, x0_mm, y0_mm, x1_mm, y1_mm, sort_order)")
    w("select s.id, v.code, v.name, v.rtype::room_type, v.x0, v.y0, v.x1, v.y1, v.ord")
    w("from scenes s, (values")
    rows = []
    for i, room in enumerate(PLAN.rooms):
        rows.append(
            f"  ({q(room.name)}, {q(room.label)}, {q(room.room_type)}, {room.x0}, {room.y0}, "
            f"{room.x1}, {room.y1}, {i * 10})"
        )
    w(",\n".join(rows))
    w(") as v(code, name, rtype, x0, y0, x1, y1, ord)")
    w(f"where s.slug = {q(SCENE_SLUG)}")
    w("on conflict (scene_id, code) do update set name = excluded.name, "
      "room_type = excluded.room_type;")
    w("")

    # -- Shops -------------------------------------------------------------
    w("-- Shops")
    w("insert into shops (slug, name, tagline, currency, status) values")
    rows = []
    for shop in catalog["shops"]:
        rows.append(
            f"  ({q(shop['id'])}, {q(shop['name'])}, {q(shop.get('tagline'))}, "
            f"{q(shop.get('currency', 'BWP'))}, 'active')"
        )
    w(",\n".join(rows))
    w("on conflict (slug) do update set name = excluded.name, "
      "tagline = excluded.tagline, status = 'active';")
    w("")

    w("-- Every seeded shop starts on the Growth plan so its products are live.")
    w("-- shop_is_live() gates public visibility on an active subscription, so")
    w("-- without this nothing would render.")
    w("insert into shop_subscriptions (shop_id, plan_id, status, current_period_end)")
    w("select s.id, p.id, 'active', now() + interval '1 year'")
    w("from shops s cross join plans p")
    w(f"where p.code = 'growth' and s.slug in "
      f"({', '.join(q(s['id']) for s in catalog['shops'])})")
    w("  and not exists (select 1 from shop_subscriptions x where x.shop_id = s.id);")
    w("")

    # -- Products ----------------------------------------------------------
    w("-- Products")
    w("insert into products (shop_id, slug, sku, name, description, category_code,")
    w("                      status, price_cents, currency, width_mm, depth_mm, height_mm,")
    w("                      thumbnail_url)")
    w("select sh.id, v.slug, v.sku, v.name, v.descr, v.cat, 'published',")
    w("       v.price, v.cur, v.w, v.d, v.h, v.thumb")
    w("from shops sh join (values")
    rows = []
    for shop in catalog["shops"]:
        for p in shop["products"]:
            # qualified id is "<shop>.<product>"; strip the shop prefix.
            slug = p["id"].split(".", 1)[1]
            dims = p.get("dimensions") or {}
            rows.append(
                f"  ({q(shop['id'])}, {q(slug)}, {q(p.get('sku'))}, {q(p['name'])},\n"
                f"   {q(p.get('description'))}, {q(p['category'])}, {cents(p.get('price'))},"
                f" {q(p.get('currency', 'BWP'))},\n"
                f"   {q(dims.get('width'))}, {q(dims.get('depth'))}, {q(dims.get('height'))},"
                f" {q(p.get('thumbnail'))})"
            )
    w(",\n".join(rows))
    w(") as v(shop, slug, sku, name, descr, cat, price, cur, w, d, h, thumb)")
    w("  on sh.slug = v.shop")
    w("on conflict (shop_id, slug) do update set")
    w("  name = excluded.name, description = excluded.description,")
    w("  price_cents = excluded.price_cents, status = 'published',")
    w("  thumbnail_url = excluded.thumbnail_url;")
    w("")

    # -- Product photographs ------------------------------------------------
    #
    # THE DATABASE PATH WAS SHOWING NO PICTURES AT ALL. `v_live_placements`
    # selects `p.thumbnail_url` and every row of `product_media`, and the
    # advert panel reads both -- but this generator wrote neither, so a
    # product carried its photographs in catalog.json and arrived from
    # Supabase with none.
    #
    # The two sources are meant to be interchangeable. That is the entire
    # reason this seed is DERIVED from the catalogue instead of hand-written,
    # and a field the catalogue has and the seed drops defeats it silently:
    # everything still works, the pictures are just missing, and only in
    # production.
    photos = []
    for shop in catalog["shops"]:
        for product in shop["products"]:
            slug = product["id"].split(".", 1)[1]
            for order, url in enumerate(product.get("media") or []):
                photos.append(f"  ({q(shop['id'])}, {q(slug)}, {q(url)}, {order})")

    if photos:
        w("-- Product photographs, thumbnail first. What a buyer actually looks")
        w("-- at -- the generated model is for judging scale by.")
        w("insert into product_media (product_id, url, kind, sort_order)")
        w("select p.id, v.url, 'image', v.ord")
        w("from products p")
        w("join shops sh on sh.id = p.shop_id")
        w("join (values")
        w(",\n".join(photos))
        w(") as v(shop, slug, url, ord)")
        w("  on sh.slug = v.shop and p.slug = v.slug")
        w("where not exists (")
        w("  select 1 from product_media m where m.product_id = p.id and m.url = v.url")
        w(");")
        w("")

    # -- Variants ----------------------------------------------------------
    w("-- Default variant per product. Objects carry a model; finishes carry a")
    w("-- material name and texture instead.")
    w("insert into product_variants (product_id, slug, name, sku, price_cents,")
    w("                              model_url, material_name, texture_url,")
    w("                              texture_tile_mm, is_default)")
    w("select p.id, 'default', v.name, v.sku, p.price_cents,")
    w("       v.model, v.material, v.texture, v.tile_mm, true")
    w("from products p")
    w("join shops sh on sh.id = p.shop_id")
    w("join (values")
    rows = []
    for shop in catalog["shops"]:
        for p in shop["products"]:
            slug = p["id"].split(".", 1)[1]
            dims = p.get("dimensions") or {}
            tile_mm = dims.get("width") if p.get("material") else None
            rows.append(
                f"  ({q(shop['id'])}, {q(slug)}, {q(p['name'])}, {q(p.get('sku'))},\n"
                f"   {q(p.get('model'))}, {q(p.get('material'))}, "
                f"{q(p.get('texture'))}, {q(tile_mm)})"
            )
    w(",\n".join(rows))
    w(") as v(shop, slug, name, sku, model, material, texture, tile_mm)")
    w("  on sh.slug = v.shop and p.slug = v.slug")
    w("on conflict (product_id, slug) do update set")
    w("  model_url = excluded.model_url, material_name = excluded.material_name,")
    w("  texture_url = excluded.texture_url;")
    w("")

    # Colour variants. Gamazine and paint are one product each, sold in many
    # shades, and each shade supplies its own material so two walls in
    # different colours stay distinguishable.
    variant_rows = []
    for shop in catalog["shops"]:
        for prod in shop["products"]:
            for var in prod.get("variants") or []:
                variant_rows.append(
                    f"  ({q(shop['id'])}, {q(prod['id'].split('.', 1)[1])}, "
                    f"{q(var['slug'])}, {q(var['name'])}, {q(var['sku'])},"
                    f" {q(var['material'])}, {q(var.get('texture'))},"
                    f" {q(var.get('swatch'))}, {q(var['isDefault'])})"
                )
    if variant_rows:
        w("-- Colour variants.")
        w("insert into product_variants (product_id, slug, name, sku,")
        w("                              material_name, texture_url, is_default)")
        w("select p.id, v.slug, v.name, v.sku, v.material, v.texture, false")
        w("from products p join shops sh on sh.id = p.shop_id")
        w("join (values")
        w(",\n".join(variant_rows))
        w(") as v(shop, prod, slug, name, sku, material, texture, swatch, is_def)")
        w("  on sh.slug = v.shop and p.slug = v.prod")
        w("on conflict (product_id, slug) do update set")
        w("  material_name = excluded.material_name;")
        w("")

    # -- Promotions --------------------------------------------------------
    # One row per distinct special, then linked to the products carrying it.
    # The end date is what makes a product go dark on its own.
    promos = {}
    for shop in catalog["shops"]:
        for prod in shop["products"]:
            promo = prod.get("promotion")
            if promo:
                promos.setdefault((shop["id"], promo["label"]), promo)

    if promos:
        w("-- Promotions. product_is_active() stops advertising a product once")
        w("-- its promotion's ends_on has passed -- no job, nothing deleted.")
        w("insert into promotions (shop_id, label, terms, starts_on, ends_on, promo_price_cents)")
        w("select sh.id, v.label, v.terms, v.starts::date, v.ends::date, v.price::integer")
        w("from shops sh join (values")
        rows = []
        for (shop_id, label), promo in promos.items():
            rows.append(
                f"  ({q(shop_id)}, {q(label)}, {q(promo.get('terms'))}, "
                f"{q(promo.get('startsOn'))}, {q(promo.get('endsOn'))}, "
                f"{cents(promo.get('promoPrice'))})"
            )
        w(",\n".join(rows))
        w(") as v(shop, label, terms, starts, ends, price) on sh.slug = v.shop")
        w("where not exists (")
        w("  select 1 from promotions x where x.shop_id = sh.id and x.label = v.label")
        w(");")
        w("")

        w("-- Link products to their promotion.")
        w("update products p set promotion_id = pr.id")
        w("from promotions pr, shops sh")
        w("where pr.shop_id = sh.id and p.shop_id = sh.id")
        w("  and (sh.slug, p.slug, pr.label) in (")
        rows = []
        for shop in catalog["shops"]:
            for prod in shop["products"]:
                promo = prod.get("promotion")
                if promo:
                    rows.append(
                        f"    ({q(shop['id'])}, {q(prod['id'].split('.', 1)[1])}, "
                        f"{q(promo['label'])})"
                    )
        w(",\n".join(rows))
        w("  );")
        w("")

    # -- Room scoping ------------------------------------------------------
    # No rows for a product means it suits ANY room, so only scoped products
    # appear here. The jute rug is deliberately absent.
    scoped = []
    for shop in catalog["shops"]:
        for prod in shop["products"]:
            for rt in prod.get("roomTypes") or []:
                scoped.append((shop["id"], prod["id"].split(".", 1)[1], rt))

    if scoped:
        w("-- Room scoping. Absent = suits any room.")
        w("insert into product_room_types (product_id, room_type)")
        w("select p.id, v.rt::room_type")
        w("from products p join shops sh on sh.id = p.shop_id")
        w("join (values")
        w(",\n".join(
            f"  ({q(a)}, {q(b)}, {q(c)})" for a, b, c in scoped))
        w(") as v(shop, slug, rt) on sh.slug = v.shop and p.slug = v.slug")
        w("on conflict (product_id, room_type) do nothing;")
        w("")

    # -- Slots -------------------------------------------------------------
    # One slot per existing placement, so the current hand-authored layout
    # becomes sellable inventory rather than being thrown away.
    all_placements = catalog["houses"].get(SCENE_SLUG, [])
    # Object slots only. A finish has no position -- it dresses a surface --
    # and gets its own slot from the wall and floor sections below.
    placements = [p for p in all_placements if not p.get("isFinish")]
    w("-- Placement slots. Derived from the hand-authored layout: each existing")
    w("-- placement becomes a slot, so the current arrangement turns into")
    w("-- inventory that can be re-sold rather than being fixed forever.")
    w("insert into placement_slots (scene_id, room_id, code, label, category_code,")
    w("                             kind, room_type, x_mm, y_mm, z_mm, rotation_deg,")
    w("                             max_width_mm, max_depth_mm, is_premium)")
    w("select sc.id, r.id, v.code, v.label, v.cat, v.kind::product_kind,")
    w("       r.room_type, v.x, v.y, v.z, v.rot, v.maxw, v.maxd, v.premium")
    w("from scenes sc")
    w("cross join (values")

    by_product = {}
    for shop in catalog["shops"]:
        for p in shop["products"]:
            by_product[p["id"]] = p

    rows = []
    for i, pl in enumerate(placements):
        product = by_product.get(pl["product"], {})
        dims = product.get("dimensions") or {}
        # Positions in the manifest are three.js metres; convert back to the
        # scene's own millimetres, which is what the database stores.
        x_m, _y_m, z_m = pl["position"]
        x_mm = round(x_m * 1000.0, 1)
        y_mm = round(-z_m * 1000.0, 1)
        code = f"{pl['room']}-{product.get('category', 'item')}-{i + 1}"
        label = f"{pl['room'].title()} {product.get('category', 'item')} position"
        maxw = (dims.get("width") or 0) * 1.15 or None
        maxd = (dims.get("depth") or 0) * 1.15 or None
        premium = product.get("category") in ("sofa", "television")
        rows.append(
            f"  ({q(pl['room'])}, {q(code)}, {q(label)}, "
            f"{q(product.get('category'))}, 'object',\n"
            f"   {x_mm}, {y_mm}, 0, {pl.get('rotationY', 0)}, "
            f"{q(round(maxw, 1) if maxw else None)}, "
            f"{q(round(maxd, 1) if maxd else None)}, {q(premium)})"
        )
    w(",\n".join(rows))
    w(") as v(room_code, code, label, cat, kind, x, y, z, rot, maxw, maxd, premium)")
    w("left join rooms r on r.scene_id = sc.id and r.code = v.room_code")
    w(f"where sc.slug = {q(SCENE_SLUG)}")
    w("on conflict (scene_id, code) do update set label = excluded.label;")
    w("")

    # -- Placements --------------------------------------------------------
    w("-- Live placements: fill each slot with the product it was authored with.")
    w("insert into placements (scene_id, slot_id, variant_id, shop_id, status, note)")
    w("select sc.id, sl.id, pv.id, p.shop_id, 'live', v.note")
    w("from scenes sc")
    w("join (values")
    rows = []
    for i, pl in enumerate(placements):
        product = by_product.get(pl["product"], {})
        code = f"{pl['room']}-{product.get('category', 'item')}-{i + 1}"
        shop_slug, product_slug = pl["product"].split(".", 1)
        rows.append(
            f"  ({q(code)}, {q(shop_slug)}, {q(product_slug)}, {q(pl.get('note'))})"
        )
    w(",\n".join(rows))
    w(") as v(slot_code, shop, product, note) on true")
    w("join placement_slots sl on sl.scene_id = sc.id and sl.code = v.slot_code")
    w("join shops sh on sh.slug = v.shop")
    w("join products p on p.shop_id = sh.id and p.slug = v.product")
    w("join product_variants pv on pv.product_id = p.id and pv.is_default")
    w(f"where sc.slug = {q(SCENE_SLUG)}")
    # ONLY ACTIVE SLOTS, and only products not already standing somewhere.
    #
    # This fills by SLOT CODE, and the codes here are the derived ones that
    # the reconciliation below retires. Without both guards, re-running the
    # seed found each retired slot empty -- the reconciliation had just moved
    # its placement onto the authored slot -- and put the product back, so the
    # house grew a second sofa, a second bed and a second rug on every apply.
    w("  and sl.is_active")
    w("  and not exists (")
    w("    select 1 from placements x")
    w("      join product_variants xv on xv.id = x.variant_id")
    w("     where xv.product_id = p.id and x.status = 'live'")
    w("       and x.scene_id = sc.id")
    w("  )")
    w("  and not exists (")
    w("    select 1 from placements x where x.slot_id = sl.id and x.status = 'live'")
    w("  );")
    w("")

    # -- Surface finishes ---------------------------------------------------
    finishes = [
        (r.name, r.finish) for r in PLAN.rooms
        if r.finish.startswith("tile_") or r.finish in ("carpet", "timber")
    ]
    w("-- Finish slots: which product dresses which room's floor. This is what")
    w("-- makes \"who supplied this floor?\" answerable for any surface.")
    w("insert into placement_slots (scene_id, room_id, code, label, category_code,")
    w("                             kind, room_type, material_name)")
    w("select sc.id, r.id, 'floor-' || r.code, r.name || ' floor', 'tile',")
    w("       'finish'::product_kind, r.room_type, v.material")
    w("from scenes sc")
    w("join (values")
    rows = [f"  ({q(name)}, {q(finish)})" for name, finish in finishes]
    w(",\n".join(rows))
    w(") as v(room_code, material) on true")
    w("join rooms r on r.scene_id = sc.id and r.code = v.room_code")
    w(f"where sc.slug = {q(SCENE_SLUG)}")
    w("on conflict (scene_id, code) do update set material_name = excluded.material_name;")
    w("")

    # -- Wall surfaces -----------------------------------------------------
    # One paintable surface per room plus the exterior, matching the skins
    # Blender exports. These are what a paint or coating is placed ON.
    w("-- Wall surfaces: one slot per room, plus the exterior.")
    w("insert into placement_slots (scene_id, room_id, code, label, category_code,")
    w("                             kind, room_type, material_name)")
    w("select sc.id, r.id, 'wall-' || r.code, r.name || ' walls', 'paint',")
    w("       'finish'::product_kind, r.room_type, 'wall.' || r.code")
    w("from scenes sc join rooms r on r.scene_id = sc.id")
    w(f"where sc.slug = {q(SCENE_SLUG)}")
    w("on conflict (scene_id, code) do update set material_name = excluded.material_name;")
    w("")
    w("insert into placement_slots (scene_id, code, label, category_code,")
    w("                             kind, room_type, material_name)")
    w("select sc.id, 'wall-exterior', 'Exterior walls', 'paint',")
    w("       'finish'::product_kind, 'outdoor'::room_type, 'wall.exterior'")
    w(f"from scenes sc where sc.slug = {q(SCENE_SLUG)}")
    w("on conflict (scene_id, code) do nothing;")
    w("")

    # -- Any other surface the catalogue dresses ---------------------------
    #
    # Floors and walls above are derived from the PLAN, because those surfaces
    # exist whether or not anybody sells something for them. This covers the
    # rest: a finish placement naming a surface that is neither, which today
    # means door hardware.
    #
    # DERIVED FROM THE CATALOGUE RATHER THAN LISTED. The first version of this
    # seeded floors and walls and nothing else, so adding the hinge produced a
    # product in the database, a variant supplying `hinge_black`, and no slot
    # for it to fill -- the placement count did not move and the hinge never
    # appeared. A new KIND of finish should not need a new section here.
    other = {}
    for pl in all_placements:
        if not pl.get("isFinish"):
            continue
        surface = pl.get("surface")
        if not surface or surface.startswith("wall.") or surface.startswith("tile_"):
            continue
        product = by_product.get(pl["product"], {})
        other[(pl["room"], surface)] = product.get("category", "decor")

    if other:
        w("-- Fitting slots: surfaces the catalogue dresses that are neither a")
        w("-- floor nor a wall. Door hardware, today.")
        w("insert into placement_slots (scene_id, room_id, code, label,"
          " category_code,")
        w("                             kind, room_type, material_name)")
        w("select sc.id, r.id, v.code, v.label, v.cat,")
        w("       'finish'::product_kind, r.room_type, v.material")
        w("from scenes sc")
        w("join (values")
        rows = []
        for (room, surface), category in sorted(other.items()):
            rows.append(
                f"  ({q(room)}, {q('fitting-' + room + '-' + surface)}, "
                f"{q(surface.replace('_', ' ').title())}, {q(category)}, {q(surface)})"
            )
        w(",\n".join(rows))
        w(") as v(room_code, code, label, cat, material) on true")
        w("join rooms r on r.scene_id = sc.id and r.code = v.room_code")
        w(f"where sc.slug = {q(SCENE_SLUG)}")
        w("on conflict (scene_id, code) do update set"
          " material_name = excluded.material_name;")
        w("")

    # -- Finish placements -------------------------------------------------
    # A finish slot names a MATERIAL; a finish product SUPPLIES one. Matching
    # them is what makes "which shop supplied this floor?" answerable from the
    # database rather than only from the baked .glb.
    #
    # Slots whose material nobody sells (the robe's carpet) stay empty, which
    # is correct: that floor is not advertising anything.
    w("-- Fill finish slots by matching the slot's material to the product")
    w("-- that supplies it. Unsold materials leave their slot empty.")
    w("insert into placements (scene_id, slot_id, variant_id, shop_id, status, note)")
    w("select sl.scene_id, sl.id, v.id, p.shop_id, 'live',")
    w("       'Floor finish supplied by ' || sh.name")
    w("from placement_slots sl")
    w("join scenes sc on sc.id = sl.scene_id")
    w("join product_variants v on v.material_name = sl.material_name")
    w("join products p on p.id = v.product_id")
    w("join shops sh on sh.id = p.shop_id")
    w("where sl.kind = 'finish'")
    # ONLY ACTIVE SLOTS. Without this the fill re-populates the derived slots
    # that the reconciliation below has just emptied and retired -- they still
    # carry a material_name and they no longer hold a placement, so they match
    # perfectly. It produced thirteen duplicate placements: every floor and
    # wall finish in the house advertised twice, once on the authored slot and
    # once on the retired one it came from.
    w("  and sl.is_active")
    w("  and sl.material_name is not null")
    w("  and p.status = 'published'")
    w(f"  and sc.slug = {q(SCENE_SLUG)}")
    w("  and not exists (")
    w("    select 1 from placements x where x.slot_id = sl.id and x.status = 'live'")
    w("  );")
    w("")

    # -- The advertising inventory -----------------------------------------
    #
    # THE SLOTS ARE AUTHORED IN THE PLAN AND MIRRORED HERE. Blender is the
    # master for structural positions -- a slot only means something if a
    # product physically fits there, and that is a modelling fact -- so these
    # rows are keyed on the stable `external_id` the plan controls and NOT on
    # anything Blender generates. A rebuild republishes the same ids and this
    # updates rather than duplicating. See migration 0006.
    #
    # 129 slots were declared and 30 existed, because the other 99 lived only
    # in slots.json and nothing ever wrote them to the database. An inventory
    # the commercial system cannot see is not inventory.
    finish_types = {
        "floor_surface", "wall_surface", "splashback", "worktop", "cabinet_front",
    }

    types = {}
    for slot in SLOTS:
        types.setdefault(slot.slot_type, (slot.category, slot.priority))

    w("-- Slot types, from the kinds the plan actually declares.")
    w("insert into slot_types (code, name, kind, category_code, default_priority)")
    w("values")
    rows = []
    for code, (category, priority) in sorted(types.items()):
        kind = "finish" if code in finish_types else "object"
        label = code.replace("_", " ").title()
        rows.append(f"  ({q(code)}, {q(label)}, {q(kind)}, {q(category or None)},"
                    f" {priority})")
    w(",\n".join(rows))
    w("on conflict (code) do update set")
    w("  name = excluded.name, kind = excluded.kind,")
    w("  category_code = excluded.category_code;")
    w("")

    w("-- Slots. Keyed on the id the plan owns, so a rebuild updates them.")
    w("insert into placement_slots (scene_id, room_id, code, external_id, label,")
    w("                             category_code, kind, room_type, origin,")
    w("                             slot_type_id, priority,")
    w("                             x_mm, y_mm, z_mm, rotation_deg,")
    w("                             max_width_mm, max_depth_mm, max_height_mm,")
    w("                             last_seen_build)")
    w("select sc.id, r.id, v.ext, v.ext, v.label,")
    w("       v.cat, st.kind, r.room_type, 'blender'::slot_origin,")
    w("       st.id, v.prio, v.x, v.y, v.z, v.rot, v.w, v.d, v.h, v.build")
    w("from scenes sc")
    w("join (values")
    rows = []
    build_stamp = datetime.now().isoformat(timespec="seconds")
    for slot in SLOTS:
        rows.append(
            f"  ({q(slot.room)}, {q(slot.id)}, {q(slot.label)}, "
            f"{q(slot.category or None)}, {q(slot.slot_type)}, {slot.priority},\n"
            f"   {slot.x}, {slot.y}, {slot.z}, {slot.rotation}, "
            f"{slot.width}, {slot.depth}, {slot.height}, {q(build_stamp)})"
        )
    w(",\n".join(rows))
    w(") as v(room_code, ext, label, cat, stype, prio, x, y, z, rot, w, d, h, build)")
    w("  on true")
    # LEFT, because a slot may belong to the house rather than to a room:
    # the exterior walls and the door hardware are sold and are in no room.
    w("left join rooms r on r.scene_id = sc.id and r.code = v.room_code")
    w("join slot_types st on st.code = v.stype")
    w(f"where sc.slug = {q(SCENE_SLUG)}")
    w("on conflict (scene_id, code) do update set")
    w("  external_id = excluded.external_id, label = excluded.label,")
    w("  category_code = excluded.category_code, origin = excluded.origin,")
    w("  slot_type_id = excluded.slot_type_id, priority = excluded.priority,")
    w("  x_mm = excluded.x_mm, y_mm = excluded.y_mm, z_mm = excluded.z_mm,")
    w("  rotation_deg = excluded.rotation_deg,")
    w("  max_width_mm = excluded.max_width_mm,")
    w("  max_depth_mm = excluded.max_depth_mm,")
    w("  max_height_mm = excluded.max_height_mm,")
    w("  last_seen_build = excluded.last_seen_build, is_active = true;")
    w("")

    w("-- ADOPT THE AUTHORED SLOT, WITHOUT MOVING THE PRODUCT.")
    w("--")
    w("-- The 19 live placements sat on DERIVED slots -- invented from the")
    w("-- placements themselves -- so every authored slot covering the same")
    w("-- position looked free. `suggest_slots` duly offered the master")
    w("-- bedroom's bed position while the Slumberland was standing in it.")
    w("--")
    w("-- The placement's own coordinates are filled in from the derived slot")
    w("-- BEFORE it is repointed. A placement inherits its slot's position when")
    w("-- it has none of its own (see v_live_placements), so repointing alone")
    w("-- would teleport every product to wherever the authored slot happens to")
    w("-- be. Copying first means the identity changes and the furniture does")
    w("-- not.")
    w("with d as (")
    w("  select s.id, s.room_id, s.category_code, s.x_mm, s.y_mm, s.z_mm,")
    w("         s.rotation_deg,")
    w("         row_number() over (partition by s.room_id, s.category_code")
    w("                            order by s.code) as rn")
    w("    from placement_slots s")
    w("   where s.origin = 'derived' and s.is_active")
    w("     and exists (select 1 from placements p")
    w("                  where p.slot_id = s.id and p.status = 'live')")
    w("), a as (")
    w("  select s.id, s.room_id, s.category_code,")
    w("         row_number() over (partition by s.room_id, s.category_code")
    w("                            order by s.priority desc, s.code) as rn")
    w("    from placement_slots s")
    w("   where s.origin = 'blender' and s.is_active")
    w("     and not exists (select 1 from placements p")
    w("                      where p.slot_id = s.id and p.status = 'live')")
    w(")")
    w("update placements p")
    w("   set x_mm = coalesce(p.x_mm, d.x_mm),")
    w("       y_mm = coalesce(p.y_mm, d.y_mm),")
    w("       z_mm = coalesce(p.z_mm, d.z_mm),")
    w("       rotation_deg = coalesce(p.rotation_deg, d.rotation_deg),")
    w("       slot_id = a.id")
    w("  from d join a on a.room_id is not distinct from d.room_id")
    w("              and a.category_code is not distinct from d.category_code")
    w("              and a.rn = d.rn")
    w(" where p.slot_id = d.id and p.status = 'live';")
    w("")

    w("-- A SECOND PASS, IGNORING THE ROOM.")
    w("--")
    w("-- Some inventory belongs to the HOUSE rather than to a room -- the")
    w("-- exterior walls, the hinges fitted to every door. The catalogue still")
    w("-- has to place them somewhere, so the hinge is placed in the hall, and")
    w("-- the derived slot inherited that room while the authored one has none.")
    w("-- Matching on room first and category second means the ordinary case")
    w("-- stays exact and the house-wide case still finds its home.")
    w("update placements p")
    w("   set x_mm = coalesce(p.x_mm, d.x_mm),")
    w("       y_mm = coalesce(p.y_mm, d.y_mm),")
    w("       z_mm = coalesce(p.z_mm, d.z_mm),")
    w("       rotation_deg = coalesce(p.rotation_deg, d.rotation_deg),")
    w("       slot_id = a.id")
    w("  from placement_slots d, placement_slots a")
    w(" where p.slot_id = d.id and p.status = 'live'")
    w("   and d.origin = 'derived' and d.is_active")
    w("   and a.origin = 'blender' and a.is_active and a.room_id is null")
    w("   and a.category_code is not distinct from d.category_code")
    w("   and a.scene_id = d.scene_id")
    w("   and not exists (select 1 from placements x")
    w("                    where x.slot_id = a.id and x.status = 'live');")
    w("")

    w("-- Retire a derived slot only when it is EMPTY and an authored slot now")
    w("-- covers the same room and category. A derived slot holding a live")
    w("-- placement is left exactly as it is: it says where a product actually")
    w("-- stands, and deactivating it would take that product out of the house.")
    w("update placement_slots d set is_active = false")
    w(" where d.origin = 'derived' and d.is_active")
    w("   and not exists (select 1 from placements p")
    w("                    where p.slot_id = d.id and p.status = 'live')")
    w("   and exists (select 1 from placement_slots a")
    w("                where a.scene_id = d.scene_id and a.origin = 'blender'")
    w("                  and (a.room_id is not distinct from d.room_id")
    w("                       or a.room_id is null)")
    w("                  and a.category_code is not distinct from d.category_code);")
    w("")

    # -- Where the catalogue says a product actually stands ----------------
    #
    # THE RECONCILIATION FROZE THESE, AND IT WAS RIGHT TO AT THE TIME. When
    # the authored slots first arrived, every live placement was moved onto
    # one WITHOUT MOVING THE PRODUCT -- the products were already where they
    # belonged and the slots were the new thing, so the coordinates were
    # pinned with `coalesce` and nothing shifted a millimetre.
    #
    # That made the placement's own x/y authoritative for ever, which is the
    # wrong way round. The catalogue is where a placement is authored; the
    # database mirrors it, exactly as it mirrors the slots. The master bed had
    # to move to the far wall when its door started opening into the room, and
    # the seed happily left the database showing it in the old position.
    w("-- The catalogue authors where a product stands; this mirrors it.")
    w("-- Deliberately NOT a coalesce: the catalogue is the source, so a")
    w("-- placement that moved there moves here. Anything placed by an")
    w("-- operator in the admin screen has no row in this list and is left")
    w("-- entirely alone.")
    w("update placements p")
    w("   set x_mm = v.x, y_mm = v.y, z_mm = v.z, rotation_deg = v.rot")
    w("  from scenes sc, product_variants pv, products pr, shops sh, (values")
    rows = []
    for pl in placements:
        x_m, _y_m, z_m = pl["position"]
        shop_slug, product_slug = pl["product"].split(".", 1)
        rows.append(
            f"  ({q(shop_slug)}, {q(product_slug)}, "
            f"{round(x_m * 1000.0, 1)}, {round(-z_m * 1000.0, 1)}, 0, "
            f"{pl.get('rotationY', 0)})"
        )
    w(",\n".join(rows))
    w(") as v(shop, product, x, y, z, rot)")
    w(" where p.scene_id = sc.id and p.status = 'live'")
    w(f"   and sc.slug = {q(SCENE_SLUG)}")
    w("   and pv.id = p.variant_id and pr.id = pv.product_id")
    w("   and sh.id = pr.shop_id")
    w("   and sh.slug = v.shop and pr.slug = v.product")
    w("   and (p.x_mm is distinct from v.x or p.y_mm is distinct from v.y")
    w("        or p.rotation_deg is distinct from v.rot);")
    w("")

    w("commit;")
    w("")

    with open(OUT_PATH, "w", encoding="utf-8") as handle:
        handle.write("\n".join(out))

    counts = {
        "shops": len(catalog["shops"]),
        "products": sum(len(s["products"]) for s in catalog["shops"]),
        "rooms": len(PLAN.rooms),
        "placements": len(placements),
        "finish slots": len(finishes),
        "authored slots": len(SLOTS),
    }
    print(f"wrote {OUT_PATH}")
    for key, value in counts.items():
        print(f"  {key:<14} {value}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
