-- =========================================================================
-- HomeLuxe 3D -- seed data
--
-- GENERATED by supabase/generate_seed.py. Do not edit by hand; edit the
-- Blender catalogue or the plan and re-run, or the database and the 3D
-- scene will disagree.
-- Generated 2026-08-15T15:56:00
-- =========================================================================

begin;

-- Product categories
insert into product_categories (code, name, kind, sort_order) values
  ('sofa', 'Sofas', 'object', 10),
  ('chair', 'Chairs', 'object', 20),
  ('table', 'Tables', 'object', 30),
  ('bed', 'Beds', 'object', 40),
  ('storage', 'Storage', 'object', 50),
  ('television', 'Televisions', 'object', 60),
  ('appliance', 'Appliances', 'object', 70),
  ('lighting', 'Lighting', 'object', 80),
  ('decor', 'Decor', 'object', 90),
  ('rug', 'Rugs', 'object', 100),
  ('bath', 'Baths', 'object', 110),
  ('basin', 'Basins', 'object', 120),
  ('toilet', 'Toilets', 'object', 130),
  ('shower', 'Showers', 'object', 140),
  ('kitchen_unit', 'Kitchen Units', 'object', 150),
  ('tile', 'Tiles', 'finish', 200),
  ('paint', 'Paint', 'finish', 210),
  ('brick', 'Brick & Cladding', 'finish', 220),
  ('flooring', 'Flooring', 'finish', 230),
  ('roofing', 'Roofing', 'finish', 240),
  ('window', 'Windows', 'object', 250),
  ('door', 'Doors', 'object', 260)
on conflict (code) do update set name = excluded.name, kind = excluded.kind;

-- Subscription plans
insert into plans (code, name, price_cents, max_products, max_placements, max_scenes, analytics, featured) values
  ('starter', 'Starter', 0, 5, 2, 1, false, false),
  ('growth', 'Growth', 75000, 40, 12, 3, true, false),
  ('premier', 'Premier', 250000, null, null, null, true, true)
on conflict (code) do nothing;

-- Scene
insert into scenes (slug, name, description, model_base, is_published) values
  ('3bed', '3 Bedroom Family Home', 'Three bedroom family home with pool, generated from blender/houseluxe.', '/models/', true)
on conflict (slug) do update set name = excluded.name, is_published = true;

-- Rooms, from blender/houseluxe/config/plan_3bed.py
insert into rooms (scene_id, code, name, room_type, x0_mm, y0_mm, x1_mm, y1_mm, sort_order)
select s.id, v.code, v.name, v.rtype::room_type, v.x0, v.y0, v.x1, v.y1, v.ord
from scenes s, (values
  ('master', 'Master Bedroom', 'bedroom', 1940.0, 1230.0, 5540.0, 4830.0, 0),
  ('ensuite', 'Ensuite', 'ensuite', 230.0, 1230.0, 1830.0, 3530.0, 10),
  ('wir', 'Walk-in Robe', 'storage', 230.0, 3640.0, 1830.0, 5440.0, 20),
  ('bed3', 'Bedroom 3', 'bedroom', 230.0, 8200.0, 3400.0, 11170.0, 30),
  ('bathroom', 'Bathroom', 'bathroom', 3510.0, 9455.0, 5600.0, 11170.0, 40),
  ('wc', 'WC', 'bathroom', 5710.0, 9455.0, 6800.0, 11170.0, 50),
  ('bed2', 'Bedroom 2', 'bedroom', 8010.0, 8200.0, 10970.0, 11170.0, 60),
  ('kitchen', 'Kitchen', 'kitchen', 5650.0, 5550.0, 9140.0, 8090.0, 70),
  ('laundry', 'Laundry', 'laundry', 11140.0, 5770.0, 12970.0, 7660.0, 80),
  ('living', 'Living', 'living', 5650.0, 230.0, 10150.0, 4230.0, 90),
  ('dining', 'Dining', 'dining', 10150.0, 230.0, 12970.0, 4230.0, 100),
  ('hall', 'Hallway', 'hallway', 1940.0, 4940.0, 5540.0, 8090.0, 110)
) as v(code, name, rtype, x0, y0, x1, y1, ord)
where s.slug = '3bed'
on conflict (scene_id, code) do update set name = excluded.name, room_type = excluded.room_type;

-- Shops
insert into shops (slug, name, tagline, currency, status) values
  ('bradlows', 'Bradlows', 'Furniture, appliances and home', 'BWP', 'active'),
  ('tubod', 'Tubod Enterprises', 'Tiles, sanitaryware and building supplies', 'BWP', 'active')
on conflict (slug) do update set name = excluded.name, tagline = excluded.tagline, status = 'active';

-- Every seeded shop starts on the Growth plan so its products are live.
-- shop_is_live() gates public visibility on an active subscription, so
-- without this nothing would render.
insert into shop_subscriptions (shop_id, plan_id, status, current_period_end)
select s.id, p.id, 'active', now() + interval '1 year'
from shops s cross join plans p
where p.code = 'growth' and s.slug in ('bradlows', 'tubod')
  and not exists (select 1 from shop_subscriptions x where x.shop_id = s.id);

-- Products
insert into products (shop_id, slug, sku, name, description, category_code,
                      status, price_cents, currency, width_mm, depth_mm, height_mm)
select sh.id, v.slug, v.sku, v.name, v.descr, v.cat, 'published',
       v.price, v.cur, v.w, v.d, v.h
from shops sh join (values
  ('bradlows', 'sandton-sofa-3', 'BRD-SAND-3S', 'Sandton 3-Seater Recliner Sofa',
   'Deep-seated three-seater in taupe bonded leather, with rolled arms and twin back cushions.', 'sofa', 1899900, 'BWP',
   2400.0, 950.0, 1020.0),
  ('bradlows', 'sandton-sofa-2', 'BRD-SAND-2S', 'Sandton 2-Seater Recliner Sofa',
   'Matching two-seater from the Sandton lounge suite.', 'sofa', 1449900, 'BWP',
   1780.0, 950.0, 1020.0),
  ('bradlows', 'sandton-recliner', 'BRD-SAND-1R', 'Sandton Recliner Armchair',
   'Single-seat recliner with extending footrest, shown reclined.', 'chair', 899900, 'BWP',
   1160.0, 1470.0, 1020.0),
  ('bradlows', 'oakwood-coffee-table', 'BRD-OAK-CT', 'Oakwood Coffee Table',
   'Dark timber coffee table with glass inset and lower shelf.', 'table', 429900, 'BWP',
   1200.0, 700.0, 450.0),
  ('bradlows', 'woven-jute-rug', 'BRD-JUTE-32', 'Woven Jute Rug 3.0 x 2.2m',
   'Hand-woven natural jute rug.', 'rug', 279900, 'BWP',
   3000.0, 2200.0, 16.0),
  ('tubod', 'pyc61001', 'TUBOD-PYC61001', 'PYC61001 Carrara Polished Porcelain 600x600',
   'White marble-effect polished porcelain floor tile with soft grey veining. Rectified edges, suitable for living areas and bedrooms.', 'tile', 18900, 'BWP',
   600.0, 600.0, 9.0),
  ('tubod', 'gamazine-exterior', 'TUBOD-GAM-EXT', 'Gamazine Exterior Textured Coating',
   'Weather-resistant textured wall coating for exterior walls. Hides hairline cracks and needs no repainting for years. Available in the full colour range.', 'paint', 14500, 'BWP',
   null, null, null),
  ('tubod', 'gamazine-interior', 'TUBOD-GAM-INT', 'Gamazine Interior Textured Coating',
   'The same textured coating in an interior grade, for feature walls and full rooms. Washable and low odour.', 'paint', 12000, 'BWP',
   null, null, null),
  ('tubod', 'wall-tile-satin-white', 'TUBOD-WT-SW36', 'Satin White Wall Tile 300x600',
   'Glazed ceramic wall tile for kitchen splashbacks and bathroom walls. Rectified edges, satin finish.', 'tile', 16500, 'BWP',
   300.0, 600.0, 8.0)
) as v(shop, slug, sku, name, descr, cat, price, cur, w, d, h)
  on sh.slug = v.shop
on conflict (shop_id, slug) do update set
  name = excluded.name, description = excluded.description,
  price_cents = excluded.price_cents, status = 'published';

-- Default variant per product. Objects carry a model; finishes carry a
-- material name and texture instead.
insert into product_variants (product_id, slug, name, sku, price_cents,
                              model_url, material_name, texture_url,
                              texture_tile_mm, is_default)
select p.id, 'default', v.name, v.sku, p.price_cents,
       v.model, v.material, v.texture, v.tile_mm, true
from products p
join shops sh on sh.id = p.shop_id
join (values
  ('bradlows', 'sandton-sofa-3', 'Sandton 3-Seater Recliner Sofa', 'BRD-SAND-3S',
   '/models/products/bradlows/sandton-sofa-3.glb', null, null, null),
  ('bradlows', 'sandton-sofa-2', 'Sandton 2-Seater Recliner Sofa', 'BRD-SAND-2S',
   '/models/products/bradlows/sandton-sofa-2.glb', null, null, null),
  ('bradlows', 'sandton-recliner', 'Sandton Recliner Armchair', 'BRD-SAND-1R',
   '/models/products/bradlows/sandton-recliner.glb', null, null, null),
  ('bradlows', 'oakwood-coffee-table', 'Oakwood Coffee Table', 'BRD-OAK-CT',
   '/models/products/bradlows/oakwood-coffee-table.glb', null, null, null),
  ('bradlows', 'woven-jute-rug', 'Woven Jute Rug 3.0 x 2.2m', 'BRD-JUTE-32',
   '/models/products/bradlows/woven-jute-rug.glb', null, null, null),
  ('tubod', 'pyc61001', 'PYC61001 Carrara Polished Porcelain 600x600', 'TUBOD-PYC61001',
   null, 'tile_pyc61001', '/textures/floor/pyc61001.jpg', 600.0),
  ('tubod', 'gamazine-exterior', 'Gamazine Exterior Textured Coating', 'TUBOD-GAM-EXT',
   null, 'gamazine_exterior', '/textures/wall/GamazineColours.png', null),
  ('tubod', 'gamazine-interior', 'Gamazine Interior Textured Coating', 'TUBOD-GAM-INT',
   null, 'gamazine_interior', '/textures/wall/GamazineColours.png', null),
  ('tubod', 'wall-tile-satin-white', 'Satin White Wall Tile 300x600', 'TUBOD-WT-SW36',
   null, 'wall_tile_satin_white', '/textures/wall/GamazineSilver.png', 300.0)
) as v(shop, slug, name, sku, model, material, texture, tile_mm)
  on sh.slug = v.shop and p.slug = v.slug
on conflict (product_id, slug) do update set
  model_url = excluded.model_url, material_name = excluded.material_name,
  texture_url = excluded.texture_url;

-- Promotions. product_is_active() stops advertising a product once
-- its promotion's ends_on has passed -- no job, nothing deleted.
insert into promotions (shop_id, label, terms, starts_on, ends_on, promo_price_cents)
select sh.id, v.label, v.terms, v.starts::date, v.ends::date, v.price::integer
from shops sh join (values
  ('bradlows', 'Winter Lounge Sale -- 20% off the Sandton suite', 'While stocks last. In-store collection or delivery within Gaborone.', '2026-06-01', '2026-12-31', null)
) as v(shop, label, terms, starts, ends, price) on sh.slug = v.shop
where not exists (
  select 1 from promotions x where x.shop_id = sh.id and x.label = v.label
);

-- Link products to their promotion.
update products p set promotion_id = pr.id
from promotions pr, shops sh
where pr.shop_id = sh.id and p.shop_id = sh.id
  and (sh.slug, p.slug, pr.label) in (
    ('bradlows', 'sandton-sofa-3', 'Winter Lounge Sale -- 20% off the Sandton suite'),
    ('bradlows', 'sandton-sofa-2', 'Winter Lounge Sale -- 20% off the Sandton suite'),
    ('bradlows', 'sandton-recliner', 'Winter Lounge Sale -- 20% off the Sandton suite')
  );

-- Room scoping. Absent = suits any room.
insert into product_room_types (product_id, room_type)
select p.id, v.rt::room_type
from products p join shops sh on sh.id = p.shop_id
join (values
  ('bradlows', 'sandton-sofa-3', 'living'),
  ('bradlows', 'sandton-sofa-3', 'dining'),
  ('bradlows', 'sandton-sofa-2', 'living'),
  ('bradlows', 'sandton-sofa-2', 'dining'),
  ('bradlows', 'sandton-recliner', 'living'),
  ('bradlows', 'sandton-recliner', 'dining'),
  ('bradlows', 'oakwood-coffee-table', 'living'),
  ('bradlows', 'oakwood-coffee-table', 'dining'),
  ('tubod', 'pyc61001', 'living'),
  ('tubod', 'pyc61001', 'dining'),
  ('tubod', 'pyc61001', 'bedroom'),
  ('tubod', 'pyc61001', 'hallway'),
  ('tubod', 'pyc61001', 'kitchen'),
  ('tubod', 'gamazine-exterior', 'outdoor'),
  ('tubod', 'gamazine-interior', 'living'),
  ('tubod', 'gamazine-interior', 'dining'),
  ('tubod', 'gamazine-interior', 'bedroom'),
  ('tubod', 'gamazine-interior', 'hallway'),
  ('tubod', 'wall-tile-satin-white', 'bathroom'),
  ('tubod', 'wall-tile-satin-white', 'ensuite'),
  ('tubod', 'wall-tile-satin-white', 'laundry'),
  ('tubod', 'wall-tile-satin-white', 'kitchen')
) as v(shop, slug, rt) on sh.slug = v.shop and p.slug = v.slug
on conflict (product_id, room_type) do nothing;

-- Placement slots. Derived from the hand-authored layout: each existing
-- placement becomes a slot, so the current arrangement turns into
-- inventory that can be re-sold rather than being fixed forever.
insert into placement_slots (scene_id, room_id, code, label, category_code,
                             kind, room_type, x_mm, y_mm, z_mm, rotation_deg,
                             max_width_mm, max_depth_mm, is_premium)
select sc.id, r.id, v.code, v.label, v.cat, v.kind::product_kind,
       r.room_type, v.x, v.y, v.z, v.rot, v.maxw, v.maxd, v.premium
from scenes sc
cross join (values
  ('living', 'living-rug-1', 'Living rug position', 'rug', 'object',
   7800.0, 2300.0, 0, 0.0, 3450.0, 2530.0, false),
  ('living', 'living-sofa-2', 'Living sofa position', 'sofa', 'object',
   7900.0, 830.0, 0, 0.0, 2760.0, 1092.5, true),
  ('living', 'living-sofa-3', 'Living sofa position', 'sofa', 'object',
   6300.0, 2500.0, 0, -90.0, 2047.0, 1092.5, true),
  ('living', 'living-chair-4', 'Living chair position', 'chair', 'object',
   9400.0, 2500.0, 0, 90.0, 1334.0, 1690.5, false),
  ('living', 'living-table-5', 'Living table position', 'table', 'object',
   7700.0, 2350.0, 0, 0.0, 1380.0, 805.0, false)
) as v(room_code, code, label, cat, kind, x, y, z, rot, maxw, maxd, premium)
left join rooms r on r.scene_id = sc.id and r.code = v.room_code
where sc.slug = '3bed'
on conflict (scene_id, code) do update set label = excluded.label;

-- Live placements: fill each slot with the product it was authored with.
insert into placements (scene_id, slot_id, variant_id, shop_id, status, note)
select sc.id, sl.id, pv.id, p.shop_id, 'live', v.note
from scenes sc
join (values
  ('living-rug-1', 'bradlows', 'woven-jute-rug', 'Anchors the seating arrangement.'),
  ('living-sofa-2', 'bradlows', 'sandton-sofa-3', 'Backs onto the south wall, 125mm clear of it.'),
  ('living-sofa-3', 'bradlows', 'sandton-sofa-2', 'Faces east toward the recliner.'),
  ('living-chair-4', 'bradlows', 'sandton-recliner', 'Footrest extends west into the open floor.'),
  ('living-table-5', 'bradlows', 'oakwood-coffee-table', 'Off-centre west, clearing the recliner footrest by ~100mm.')
) as v(slot_code, shop, product, note) on true
join placement_slots sl on sl.scene_id = sc.id and sl.code = v.slot_code
join shops sh on sh.slug = v.shop
join products p on p.shop_id = sh.id and p.slug = v.product
join product_variants pv on pv.product_id = p.id and pv.is_default
where sc.slug = '3bed'
  and not exists (
    select 1 from placements x where x.slot_id = sl.id and x.status = 'live'
  );

-- Finish slots: which product dresses which room's floor. This is what
-- makes "who supplied this floor?" answerable for any surface.
insert into placement_slots (scene_id, room_id, code, label, category_code,
                             kind, room_type, material_name)
select sc.id, r.id, 'floor-' || r.code, r.name || ' floor', 'tile',
       'finish'::product_kind, r.room_type, v.material
from scenes sc
join (values
  ('master', 'tile_pyc61001'),
  ('wir', 'carpet'),
  ('bed3', 'tile_pyc61001'),
  ('bed2', 'tile_pyc61001'),
  ('living', 'tile_pyc61001'),
  ('dining', 'tile_pyc61001'),
  ('hall', 'tile_pyc61001')
) as v(room_code, material) on true
join rooms r on r.scene_id = sc.id and r.code = v.room_code
where sc.slug = '3bed'
on conflict (scene_id, code) do update set material_name = excluded.material_name;

-- Fill finish slots by matching the slot's material to the product
-- that supplies it. Unsold materials leave their slot empty.
insert into placements (scene_id, slot_id, variant_id, shop_id, status, note)
select sl.scene_id, sl.id, v.id, p.shop_id, 'live',
       'Floor finish supplied by ' || sh.name
from placement_slots sl
join scenes sc on sc.id = sl.scene_id
join product_variants v on v.material_name = sl.material_name
join products p on p.id = v.product_id
join shops sh on sh.id = p.shop_id
where sl.kind = 'finish'
  and sl.material_name is not null
  and p.status = 'published'
  and sc.slug = '3bed'
  and not exists (
    select 1 from placements x where x.slot_id = sl.id and x.status = 'live'
  );

commit;
