import React, { useEffect, useRef, useState } from 'react';
import * as THREE from 'three';
import { OrbitControls, DragControls, TransformControls } from 'three-stdlib';

import {
  loadHouse,
  disposeHouse,
  getDracoLoader,
  disposeDracoLoader,
  createHouseMaterials,
  disposeHouseMaterials,
  HOUSE_VIEWS,
} from './house';
import { loadProducts, disposeProducts } from './products';
import { createAtmosphere } from './atmosphere/Atmosphere';
import {
  createTourController,
  loadCharacter,
  disposeCharacter,
  TourPad,
  TOUR_START,
} from './tour';

const CanvasContainer = ({ currentRoom, currentIndex, isAdmin }) => {
  const canvasRef = useRef(null);
  const sceneRef = useRef(null);
  const rendererRef = useRef(null);
  const cameraRef = useRef(null);
  const controlsRef = useRef(null);
  const productsRef = useRef(null);
  const houseRef = useRef(null);
  const houseMaterialsRef = useRef(null);
  const atmosphereRef = useRef(null);
  const tourRef = useRef(null);
  const characterRef = useRef(null);
  const [touring, setTouring] = useState(false);

  useEffect(() => {
    if (!canvasRef.current) return;

    // Initialize Three.js scene
    let disposed = false;

    const scene = new THREE.Scene();
    // Background and fog are set by the atmosphere below, so the sky, the
    // fog and the cloud layers cannot drift out of agreement.

    const camera = new THREE.PerspectiveCamera(
      55,
      canvasRef.current.clientWidth / canvasRef.current.clientHeight,
      0.1,
      1000
    );

    const renderer = new THREE.WebGLRenderer({ antialias: true, alpha: true });
    renderer.setSize(canvasRef.current.clientWidth, canvasRef.current.clientHeight);
    renderer.shadowMap.enabled = true;
    renderer.shadowMap.type = THREE.PCFSoftShadowMap;
    renderer.outputColorSpace = THREE.SRGBColorSpace;
    renderer.toneMapping = THREE.ACESFilmicToneMapping;
    renderer.toneMappingExposure = 1;

    canvasRef.current.appendChild(renderer.domElement);

    // Orbit Controls
    const orbitControls = new OrbitControls(camera, renderer.domElement);
    orbitControls.enableDamping = true;
    orbitControls.dampingFactor = 0.05;
    orbitControls.screenSpacePanning = true;
    // The house is ~14m across, so the old 10m ceiling put the camera inside
    // the building at full zoom-out.
    orbitControls.minDistance = 1.5;
    orbitControls.maxDistance = 75;   // far enough to see the whole 30x40 yard
    orbitControls.maxPolarAngle = Math.PI / 2;
    orbitControls.enabled = true;

    // Store references
    sceneRef.current = scene;
    rendererRef.current = renderer;
    cameraRef.current = camera;
    controlsRef.current = orbitControls;

    // ---- Sky, clouds, fog ------------------------------------------------
    const atmosphere = createAtmosphere();
    atmosphere.applyTo(scene);
    atmosphereRef.current = atmosphere;

    // ---- The house and its yard ------------------------------------------
    // Loaded from the per-component GLBs generated by blender/houseluxe.
    // Textures are applied here, in three.js, keyed by Blender material name.
    const houseMaterials = createHouseMaterials({
      anisotropy: renderer.capabilities.getMaxAnisotropy(),
    });
    houseMaterialsRef.current = houseMaterials;

    // Products are loaded AFTER the house and parented to it, not to the
    // scene. The house group carries the recentring offset; a product added
    // to the scene instead would sit at raw Blender coordinates, metres away.
    // Chaining also avoids racing the two loads against each other.
    (async () => {
      try {
        const { house, errors, stats } = await loadHouse({
          materials: houseMaterials,
        });

        // The component can unmount while the GLBs are still in flight.
        if (disposed) {
          disposeHouse(house);
          return;
        }

        scene.add(house);
        houseRef.current = house;

        if (errors.length) {
          console.error(
            '[house] %d part(s) failed to load:',
            errors.length,
            errors.map((e) => `${e.file}: ${e.error?.message ?? e.error}`)
          );
        }
        if (stats.untextured.size) {
          console.warn(
            '[house] no three.js material for:',
            [...stats.untextured].join(', ')
          );
        }

        // ---- Shop products ---------------------------------------------
        // Real retail furniture from the Blender catalogue, positioned by
        // the manifest. The old primitive sofas and sofa.glb are gone.
        const { group, placed, errors: productErrors } = await loadProducts({
          house: '3bed',
          materials: houseMaterials,
          dracoLoader: getDracoLoader(),
        });

        if (disposed) {
          disposeProducts(group);
          return;
        }

        house.add(group);
        productsRef.current = group;

        if (productErrors.length) {
          console.error(
            '[products] %d problem(s):',
            productErrors.length,
            productErrors.map(
              (e) => `${e.stage}:${e.productId ?? ''} ${e.error?.message}`
            )
          );
        }
        console.log(`[products] placed ${placed.length} item(s)`);

        // ---- Walk-through tour ------------------------------------------
        // The character goes in the SCENE, not the house group -- unlike the
        // products. The controller drives the camera and fires raycasts, and
        // both work in world space; parenting the character to the recentred
        // house would leave it offset from its own camera by ~7 metres.
        // TOUR_START is therefore given in world coordinates.
        const character = await loadCharacter({
          materials: houseMaterials,
          dracoLoader: getDracoLoader(),
        });
        if (disposed) {
          disposeCharacter(character);
          return;
        }

        scene.add(character);
        characterRef.current = character;

        // Raycasts read world matrices, which are otherwise only refreshed
        // during render -- so the first ground probe would use stale ones.
        house.updateMatrixWorld(true);

        // Ground = anything you can stand on. Walls = anything that stops
        // you. Doors are in NEITHER: every door is treated as open, and
        // doorways are real gaps in the wall geometry.
        const part = (id) => house.userData.parts?.[id];
        const groundObjects = [
          'slab', 'floors', 'porch', 'yard_ground', 'yard_paving', 'yard_beds',
        ].map(part).filter(Boolean);
        const wallObjects = [
          'walls_exterior', 'walls_interior', 'pool_fence', 'yard_fence',
        ].map(part).filter(Boolean);

        const tour = createTourController({
          character,
          camera,
          controls: orbitControls,
          groundObjects,
          wallObjects,
          start: TOUR_START.position,
          startHeading: TOUR_START.heading,
        });
        tour.attach(window);
        tourRef.current = tour;

        // Deep link: /#tour drops the visitor straight onto the driveway.
        // Handy for "take the tour" links in an advert.
        if (window.location.hash === '#tour') {
          tour.enter();
          setTouring(true);
        }
      } catch (error) {
        console.error('[scene] failed to load:', error);
      }
    })();

    // Lighting setup
    setupLighting(scene, atmosphere.sunDirection);

    // Set initial camera position
    const view = HOUSE_VIEWS.overview;
    camera.position.set(...view.position);
    camera.lookAt(...view.target);
    orbitControls.target.set(...view.target);

    // Animation loop
    const clock = new THREE.Clock();
    const animate = () => {
      requestAnimationFrame(animate);
      const delta = clock.getDelta();

      // The tour takes the camera over when active; OrbitControls is
      // disabled then, so only one of these ever moves it.
      if (tourRef.current?.active) {
        tourRef.current.update(delta);
      } else {
        orbitControls.update();
      }

      atmosphere.update(delta);

      // Keep the sky centred on the viewer so it can never be reached.
      atmosphere.group.position.set(camera.position.x, 0, camera.position.z);

      renderer.render(scene, camera);
    };
    animate();

    // Handle resize
    const handleResize = () => {
      const width = canvasRef.current.clientWidth;
      const height = canvasRef.current.clientHeight;
      camera.aspect = width / height;
      camera.updateProjectionMatrix();
      renderer.setSize(width, height);
    };

    window.addEventListener('resize', handleResize);

    // Cleanup
    return () => {
      disposed = true;
      window.removeEventListener('resize', handleResize);

      tourRef.current?.detach(window);
      tourRef.current = null;
      disposeCharacter(characterRef.current);
      characterRef.current = null;
      disposeProducts(productsRef.current);
      disposeHouse(houseRef.current);
      disposeHouseMaterials(houseMaterialsRef.current);
      disposeDracoLoader();   // shuts down the decoder's Web Workers
      atmosphereRef.current?.dispose();
      productsRef.current = null;
      houseRef.current = null;
      houseMaterialsRef.current = null;
      atmosphereRef.current = null;

      if (rendererRef.current && canvasRef.current) {
        canvasRef.current.removeChild(rendererRef.current.domElement);
        rendererRef.current.dispose();
      }
    };
  }, []);

  useEffect(() => {
    // Update canvas title based on current room and index
    const canvasTitle = document.getElementById('canvas-title');
    if (canvasTitle) {
      if (currentRoom === 'living-room') {
        canvasTitle.textContent = 'Living Room - Click furniture to explore';
      } else {
        canvasTitle.textContent = `Coming soon - ${currentRoom.replace('-', ' ').replace(/\b\w/g, l => l.toUpperCase())}`;
      }
    }
  }, [currentRoom, currentIndex]);

  // The tour only exists once the scene has finished loading, so both of
  // these no-op until then rather than throwing.
  const startTour = () => {
    const tour = tourRef.current;
    if (!tour) return;
    tour.toggle();
    setTouring(tour.active);
  };

  const exitTour = () => {
    tourRef.current?.exit();
    setTouring(false);
  };

  return (
    <div id="canvas-container">
      <div className="canvas-overlay" id="canvas-title">Living Room - Click furniture to explore</div>
      <div className="rotation-indicator">
        <span className="rotation-icon">↻</span>
        <span id="rotation-text">360° View Active</span>
      </div>
      <div className="camera-controls">
        <div className="edit-controls">
          <button className="edit-btn" id="drag-mode" title="Drag Mode - Click and drag furniture" style={{ display: 'none' }}>✋</button>
          <button className="edit-btn" id="transform-mode" title="Transform Mode - Edit position/rotation/scale" style={{ display: isAdmin ? 'block' : 'none' }}>🔧</button>
        </div>
        <div className="transform-sub-controls" id="transform-sub-controls" style={{ display: 'none' }}>
          <button className="transform-sub-btn" id="translate-mode" title="Move">↔️</button>
          <button className="transform-sub-btn" id="rotate-mode" title="Rotate">🔄</button>
          <button className="transform-sub-btn" id="scale-mode" title="Scale">📏</button>
        </div>
        <button className="camera-btn" id="camera-front" title="Front View">👁️</button>
        <button className="camera-btn" id="camera-side" title="Side View">👈</button>
        <button className="camera-btn" id="camera-top" title="Top View">⬇️</button>
        <button className="camera-btn" id="camera-reset" title="Reset View">🔄</button>
        <button
          className="camera-btn"
          id="tour-mode"
          title={touring ? 'Exit walk-through' : 'Walk through the property'}
          onClick={startTour}
          style={{ background: touring ? '#1f6feb' : undefined }}
        >
          🚶
        </button>
      </div>

      {touring && (
        <TourPad
          onPress={(dir) => tourRef.current?.setButton(dir, true)}
          onRelease={(dir) => tourRef.current?.setButton(dir, false)}
          onExit={exitTour}
        />
      )}

      <div ref={canvasRef} style={{ width: '100%', height: '100%' }}></div>
    </div>
  );
};

// Lighting setup function.
//
// There is no ground plane any more -- the lawn from blender/houseluxe is the
// ground, and a second flat plane would z-fight with it.
function setupLighting(scene, sunDirection) {
  // Sky/ground hemisphere does most of the ambient work and keeps interiors
  // from going flat grey now that the ceiling can be closed over them.
  const hemi = new THREE.HemisphereLight(0xbcd6f0, 0x6b7355, 0.85);
  scene.add(hemi);

  const ambientLight = new THREE.AmbientLight(0xffffff, 0.25);
  scene.add(ambientLight);

  // Sun, aimed along the atmosphere's sun direction so shadows fall away
  // from the bright quarter of the sky.
  const mainLight = new THREE.DirectionalLight(0xfff4e6, 2.2);
  mainLight.position.copy(sunDirection).multiplyScalar(45);
  mainLight.castShadow = true;

  // The frustum now has to cover the whole 30x40 yard, not just the house.
  // Sized too tightly, trees at the boundary stop casting entirely.
  const extent = 26;
  mainLight.shadow.camera.left = -extent;
  mainLight.shadow.camera.right = extent;
  mainLight.shadow.camera.top = extent;
  mainLight.shadow.camera.bottom = -extent;
  mainLight.shadow.camera.near = 1;
  mainLight.shadow.camera.far = 140;
  mainLight.shadow.mapSize.width = 2048;
  mainLight.shadow.mapSize.height = 2048;
  // Wider frustum means coarser texels, so the bias has to grow with it.
  mainLight.shadow.bias = -0.0009;
  mainLight.shadow.normalBias = 0.03;
  scene.add(mainLight);

  const fillLight = new THREE.DirectionalLight(0x87ceeb, 0.35);
  fillLight.position.set(-12, 8, -10);
  scene.add(fillLight);

  // Interior fills, placed just under the 2.4m ceiling in the living zone
  // and the kitchen so the inside is readable when the roof is on.
  [
    [2.7, 2.2, 2.7],
    [-0.6, 2.2, -1.6],
    [-3.5, 2.2, 3.0],
  ].forEach(([x, y, z]) => {
    const lamp = new THREE.PointLight(0xfff8dc, 8, 9);
    lamp.position.set(x, y, z);
    scene.add(lamp);
  });
}

// GLTF loading function

export default CanvasContainer;
