/**
 * House part manifest.
 *
 * One entry per GLB exported by `blender/houseluxe`. This list mirrors the
 * component classes on the Blender side, and that correspondence is the whole
 * reason the house was split into separate files: a part can be hidden,
 * reloaded or swapped on its own, at runtime, without touching the others.
 *
 * Adding a part to the building is a new Component in Blender plus one line
 * here.
 */

export const HOUSE_BASE_PATH = "/models/house/";

/**
 * Every part defaults to visible: the house should look like a finished house.
 *
 * Roof and ceiling are the two you will most often want off -- with them on you
 * cannot see into the rooms from outside. Rather than defaulting them off,
 * toggle them at runtime:
 *
 *     setPartVisible(house, 'roof', false);
 *     setPartVisible(house, 'ceiling', false);
 */
export const HOUSE_PARTS = [
  { id: "slab",           file: "slab.glb",           label: "Floor slab",     visible: true,  castShadow: false, receiveShadow: true },
  { id: "floors",         file: "floors.glb",         label: "Floor finishes", visible: true,  castShadow: false, receiveShadow: true },
  { id: "walls_exterior", file: "walls_exterior.glb", label: "Exterior walls", visible: true,  castShadow: true,  receiveShadow: true },
  { id: "walls_interior", file: "walls_interior.glb", label: "Interior walls", visible: true,  castShadow: true,  receiveShadow: true },
  // The paintable skin over every wall face, one surface per room. This is
  // what a paint or coating product is applied to; the walls themselves are
  // structure and keep their brick and plaster.
  { id: "wall_finishes",  file: "wall_finishes.glb",  label: "Wall finishes",  visible: true,  castShadow: false, receiveShadow: true },
  { id: "windows",        file: "windows.glb",        label: "Windows",        visible: true,  castShadow: false, receiveShadow: false },
  { id: "doors",          file: "doors.glb",          label: "Doors",          visible: true,  castShadow: true,  receiveShadow: true },
  // THE CEILING MUST CAST. With this false the sun went straight through it
  // into every room, which is why the interiors looked as though the house
  // was full of holes: the roof above blocked the light, the ceiling below
  // did not, and the gap between them let the sun land on the furniture.
  // A ceiling is the surface that actually separates a room from the sky.
  { id: "ceiling",        file: "ceiling.glb",        label: "Ceiling",        visible: true,   castShadow: true,  receiveShadow: true },
  { id: "porch",          file: "porch.glb",          label: "Porch",          visible: true,  castShadow: true,  receiveShadow: true },
  { id: "roof",           file: "roof.glb",           label: "Roof",           visible: true,   castShadow: true,  receiveShadow: false },
];

export const SITE_BASE_PATH = "/models/site/";

/**
 * Yard parts, generated by `blender/houseluxe/components/site/`.
 *
 * Loaded into the same group as the house and recentred on the HOUSE, not on
 * themselves — the two were modelled in one coordinate system and must not
 * drift apart.
 *
 * `yard_ground` does not cast: it is the thing everything else casts onto,
 * and self-shadowing a 30x40 surface buys nothing but acne.
 */
export const SITE_PARTS = [
  { id: "yard_ground",   file: "yard_ground.glb",   label: "Ground & lawn",  visible: true, castShadow: false, receiveShadow: true },
  { id: "yard_paving",   file: "yard_paving.glb",   label: "Paving",         visible: true, castShadow: false, receiveShadow: true },
  { id: "yard_beds",     file: "yard_beds.glb",     label: "Garden beds",    visible: true, castShadow: false, receiveShadow: true },
  { id: "pool",          file: "pool.glb",          label: "Pool",           visible: true, castShadow: false, receiveShadow: true },
  { id: "pool_fence",    file: "pool_fence.glb",    label: "Pool barrier",   visible: true, castShadow: true,  receiveShadow: false },
  { id: "yard_planting", file: "yard_planting.glb", label: "Planting",       visible: true, castShadow: true,  receiveShadow: true },
  { id: "yard_hedges",   file: "yard_hedges.glb",   label: "Hedges",         visible: true, castShadow: true,  receiveShadow: true },
  { id: "yard_fence",    file: "yard_fence.glb",    label: "Boundary fence", visible: true, castShadow: true,  receiveShadow: true },
];

/**
 * Named viewpoints, in house-local metres AFTER recentring (origin at the
 * middle of the footprint, Y up, floor at Y=0).
 *
 * Derived from the plan: living/dining occupies the south-east quarter, so
 * its centre sits at roughly +2.7 X, +2.7 Z once the house is centred.
 */
export const HOUSE_VIEWS = {
  // Pulled back to take in the yard now that there is one.
  overview: { position: [24, 17, 26], target: [1, 1.0, 0] },
  living:   { position: [4.5, 2.2, 6.5], target: [2.7, 1.2, 2.7] },
  kitchen:  { position: [1.5, 2.2, 1.5], target: [-0.6, 1.2, -1.6] },
  entry:    { position: [-1.0, 2.0, 9.0], target: [-1.0, 1.3, 4.5] },
  pool:     { position: [16, 6, 14], target: [11.4, 0.4, 0.9] },
};

/** Centre of the open living/dining zone. Placeholder furniture sits here. */
export const LIVING_ZONE_CENTRE = [2.7, 0, 2.7];
