/**
 * The tour character model.
 *
 * Generated by `blender/houseluxe/components/character.py`, facing +Y in
 * Blender, which the exporter turns into -Z in three.js. The controller's
 * heading of 0 means -Z for exactly that reason: they have to agree, or the
 * character walks backwards.
 */

import * as THREE from "three";
import { GLTFLoader } from "three-stdlib";

export const TOUR_CHARACTER_URL = "/models/tour/character.glb";

/**
 * Where the visitor starts, in house-local metres AFTER recentring.
 *
 * On the driveway at the street end, facing the front door — so the tour
 * begins by walking up to the house rather than inside it, which is what
 * "come from outside" means.
 *
 * Derived from the site plan: the driveway runs x 3,800..7,400 at
 * y -14,000..-1,500 in Blender millimetres, so its centre line is x 5,600.
 * Recentring shifts the house by about (-6.6, +0.3, +4.95) metres.
 */
export const TOUR_START = {
  position: [-1.0, 13.5],   // [x, z] metres
  heading: 0,               // 0 = facing -Z = north = toward the house
};

/** Load the character, or return null if it is missing. */
export async function loadCharacter({ materials = null, dracoLoader = null } = {}) {
  const loader = new GLTFLoader();
  if (dracoLoader) loader.setDRACOLoader(dracoLoader);

  const scene = await new Promise((resolve, reject) => {
    loader.load(TOUR_CHARACTER_URL, (gltf) => resolve(gltf.scene), undefined, reject);
  });

  scene.name = "tour-character";
  scene.visible = false;   // shown only while the tour is running

  scene.traverse((child) => {
    if (!child.isMesh) return;
    child.castShadow = true;
    child.receiveShadow = true;
    const override = materials?.get(child.material?.name);
    if (override) child.material = override;
  });

  return scene;
}

/** Free the character's geometry. */
export function disposeCharacter(character) {
  if (!character) return;
  character.traverse((child) => {
    if (child.isMesh) child.geometry?.dispose();
  });
}
